### ISSUE TITLE
Add Questions for 2D arrays, binary search and bit manipulation

### ISSUE THREAD

**Issue by sneha31415** [Tushar2001bbdu/DSA_Using_Java#1]
### I would like to suggest adding some DSA-related practice questions on the following topics:

- 2D Arrays
- Binary Search
- Bit Manipulation

These topics are commonly tested in coding interviews and competitive programming, and providing questions for them would greatly enhance the repository’s usefulness for learners. 

Below are a few question ideas for each topic:

### 2D arrays:
1. Wave print
2. spiral print
3. rotate image
4. staircase search

### binary search
1. first and last occurance in array
2. search in rotated sorted array
3. find square root
4. aggressive cows
5. book allocation

### bit manipulation
1. find unique number
2. find two unique number
3. count set bits
4. decimal to binary
5. fast exponentiation

This will make the repository more useful to users

**Comment by Tushar2001bbdu** [comment]
i assign you this issue
